version: '3.8'

services:
  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  celery_worker:
    build: .
    container_name: fiatjafbuzz_celery_worker
    command: celery -A fiatjafbuzz.celery_app worker --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

  celery_beat:
    build: .
    container_name: fiatjafbuzz_celery_beat
    command: celery -A fiatjafbuzz.celery_app beat --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

  flower:
    build: .
    container_name: fiatjafbuzz_flower
    command: celery -A fiatjafbuzz.celery_app flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  redis_data:
